### ISSUE TITLE
.

### ISSUE THREAD

**Issue by loqusion** [FollieHiyuki/FollieHiyuki#1]
![0f7103mizx641](https://user-images.githubusercontent.com/38332081/189469531-69080ec0-10e1-440a-bd1e-2adf19641617.jpg)

**Comment by loqusion** [comment]
Misusing github issues is a new low for me

**Comment by folliehiyuki** [comment]
I see you already ~~forked~~ took it so closing as completed :smile: 

I'm surprised someone got interested in my collection of random anime images and even wasted a few minutes opening a Github issue saying so.
